### ISSUE TITLE
how to display all result? 

### ISSUE THREAD

**Issue by JohnLoveMm** [Wuziyi616/Artificial_Intelligence_Project1#3]
大佬您好，当我运行您的程序之后，发现这真的是一个很好玩的程序。但是我觉得搜索出来的结果应该不止一个，我想查看所有的搜索结果，我该怎么做？

**Comment by Wuziyi616** [comment]
感谢关注！非常遗憾的是我的程序基于深度优先搜索，因此确实只会给出一个解，毕竟当时考虑的是求解速度而不求全面性

**Comment by JohnLoveMm** [comment]
感谢您的回复，您的想法确实厉害，感谢！
